apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: basic-redis
  labels:
    name: redis
spec:
  selector:
    name: redis
  ports:
  - name: redis6379
    port: 6379
    targetPort: 6379
    protocol: TCP
  # กำหนดให้ clusterIP เป็น none
  # จะชี้ไปที่ pod เดียวเสมอ
  clusterIP: None